# Generated by Django 2.0.7 on 2018-08-22 03:34

from django.db import migrations, models
import djongo.models.fields
import reportesMongo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('full_name', models.CharField(max_length=255)),
                ('ordenes', djongo.models.fields.ArrayModelField(model_container=reportesMongo.models.Orden)),
            ],
        ),
    ]
