# Generated by Django 2.0.7 on 2018-08-22 04:06

from django.db import migrations, models
import djongo.models.fields
import reportesMongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('reportesMongo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('detalle', djongo.models.fields.ArrayModelField(model_container=reportesMongo.models.OrdenDetalle)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField()),
                ('productName', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
            ],
        ),
    ]
