# Generated by Django 2.0.7 on 2018-08-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportesMongo', '0002_orden_ordendetalle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenDetalle',
        ),
    ]
